ALTER TABLE public.client_filter_preferences
  ADD COLUMN IF NOT EXISTS min_bedrooms integer,
  ADD COLUMN IF NOT EXISTS max_bedrooms integer,
  ADD COLUMN IF NOT EXISTS min_bathrooms integer,
  ADD COLUMN IF NOT EXISTS max_bathrooms integer,
  ADD COLUMN IF NOT EXISTS pet_friendly_required boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS furnished_required boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS amenities_required jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS property_types jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS location_zones jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS interested_in_properties boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS interested_in_motorcycles boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS interested_in_bicycles boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS interested_in_vehicles boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS moto_types jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS moto_price_min numeric,
  ADD COLUMN IF NOT EXISTS moto_price_max numeric,
  ADD COLUMN IF NOT EXISTS moto_year_min integer,
  ADD COLUMN IF NOT EXISTS moto_year_max integer,
  ADD COLUMN IF NOT EXISTS bicycle_types jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS bicycle_price_min numeric,
  ADD COLUMN IF NOT EXISTS bicycle_price_max numeric,
  ADD COLUMN IF NOT EXISTS vehicle_types jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS vehicle_price_min numeric,
  ADD COLUMN IF NOT EXISTS vehicle_price_max numeric;