// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/utils/prodLogger';

const PRODUCTION_PROJECT_ID = 'vplgtcguxujxwrgguxqq';
const SUPABASE_URL = `https://${PRODUCTION_PROJECT_ID}.supabase.co`;
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbGd0Y2d1eHVqeHdyZ2d1eHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDI5MDIsImV4cCI6MjA2MzU3ODkwMn0.-TzSQ-nDho4J6TftVF4RNjbhr5cKbknQxxUT-AaSIJU';

// Backend Isolation Lockdown — Absolute Enforcement
if (!SUPABASE_URL.includes(PRODUCTION_PROJECT_ID)) {
  const errorMsg = `[CRITICAL] UNAUTHORIZED BACKEND DETECTED! Only project ${PRODUCTION_PROJECT_ID} is allowed.`;
  logger.error(errorMsg);
  // Force reset if hijacked
  window.location.reload();
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      // Fetch with 30s timeout — prevent AI request timeouts while allowing for slower mobile networks
      fetch: (url: RequestInfo | URL, options?: RequestInit) => {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 30000); 
        return fetch(url, { ...options, signal: controller.signal })
          .finally(() => clearTimeout(timeoutId));
      },
    },
    realtime: {
      params: {
        eventsPerSecond: 20, // Increased from 10 for smoother real-time UX
      },
      // Explicit heartbeat + exponential reconnect backoff
      // Reduced heartbeat to 20s to detect drops faster on flaky networks (mobile)
      heartbeatIntervalMs: 20000,
      reconnectAfterMs: (tries: number) => {
        // Optimized backoff: 1s, 2s, 4s, 8s, 16s, then max 30s
        return Math.min(Math.pow(2, tries) * 1000, 30000);
      },
    },
  }
);



